<?php

use Illuminate\Database\Seeder;

class LaporanBukuBesarPenyesuaiansTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
				[
					'account_id' => 1,
					'tanggal' => now(),
					'saldo_awals_id' => 1,
					'crj_id' => null,
					'cpj_id' => null,
					'purchasejournal_id' => null,
					'salesjournal_id' => null,
					'retur_penjualan_id' => null,
					'retur_pembelian_id' => null,
					'cash_bank_ins_id' => null,
					'cash_bank_outs_id' => null,
					'jurnal_umums_id' => null,
					'pettycash_id' => null,
					'jurnalpenyesuaians_id' => null,
					'debet'      => 264463000,
					'kredit'     => 0,
					'created_at' => now(),
					'updated_at' => now(),
				],
				[
					'account_id' => 2,
					'tanggal' => now(),
					'saldo_awals_id' => 2,
					'crj_id' => null,
					'cpj_id' => null,
					'purchasejournal_id' => null,
					'salesjournal_id' => null,
					'retur_penjualan_id' => null,
					'retur_pembelian_id' => null,
					'cash_bank_ins_id' => null,
					'cash_bank_outs_id' => null,
					'jurnal_umums_id' => null,
					'pettycash_id' => null,
					'jurnalpenyesuaians_id' => null,
					'debet'      => 6000000,
					'kredit'     => 0,
					'created_at' => now(),
					'updated_at' => now(),
				],
				[
					'account_id' => 4,
					'tanggal' => now(),
					'saldo_awals_id' => 3,
					'crj_id' => null,
					'cpj_id' => null,
					'purchasejournal_id' => null,
					'salesjournal_id' => null,
					'retur_penjualan_id' => null,
					'retur_pembelian_id' => null,
					'cash_bank_ins_id' => null,
					'cash_bank_outs_id' => null,
					'jurnal_umums_id' => null,
					'pettycash_id' => null,
					'jurnalpenyesuaians_id' => null,
					'debet'      => 110000000,
					'kredit'     => 0,
					'created_at' => now(),
					'updated_at' => now(),
				],
				[
					'account_id' => 5,
					'tanggal' => now(),
					'saldo_awals_id' => 4,
					'crj_id' => null,
					'cpj_id' => null,
					'purchasejournal_id' => null,
					'salesjournal_id' => null,
					'retur_penjualan_id' => null,
					'retur_pembelian_id' => null,
					'cash_bank_ins_id' => null,
					'cash_bank_outs_id' => null,
					'jurnal_umums_id' => null,
					'pettycash_id' => null,
					'jurnalpenyesuaians_id' => null,
					'debet'      => 0,
					'kredit'     => 7200000,
					'created_at' => now(),
					'updated_at' => now(),
				],
				[
					'account_id' => 6,
					'tanggal' => now(),
					'saldo_awals_id' => 5,
					'crj_id' => null,
					'cpj_id' => null,
					'purchasejournal_id' => null,
					'salesjournal_id' => null,
					'retur_penjualan_id' => null,
					'retur_pembelian_id' => null,
					'cash_bank_ins_id' => null,
					'cash_bank_outs_id' => null,
					'jurnal_umums_id' => null,
					'pettycash_id' => null,
					'jurnalpenyesuaians_id' => null,
					'debet'      => 180000000,
					'kredit'     => 0,
					'created_at' => now(),
					'updated_at' => now(),
				],
				[
					'account_id' => 7,
					'tanggal' => now(),
					'saldo_awals_id' => 6,
					'crj_id' => null,
					'cpj_id' => null,
					'purchasejournal_id' => null,
					'salesjournal_id' => null,
					'retur_penjualan_id' => null,
					'retur_pembelian_id' => null,
					'cash_bank_ins_id' => null,
					'cash_bank_outs_id' => null,
					'jurnal_umums_id' => null,
					'pettycash_id' => null,
					'jurnalpenyesuaians_id' => null,
					'debet'      => 13600000,
					'kredit'     => 0,
					'created_at' => now(),
					'updated_at' => now(),
				],
				[
					'account_id' => 9,
					'tanggal' => now(),
					'saldo_awals_id' => 7,
					'crj_id' => null,
					'cpj_id' => null,
					'purchasejournal_id' => null,
					'salesjournal_id' => null,
					'retur_penjualan_id' => null,
					'retur_pembelian_id' => null,
					'cash_bank_ins_id' => null,
					'cash_bank_outs_id' => null,
					'jurnal_umums_id' => null,
					'pettycash_id' => null,
					'jurnalpenyesuaians_id' => null,
					'debet'      => 8000000,
					'kredit'     => 0,
					'created_at' => now(),
					'updated_at' => now(),
				],
				[
					'account_id' => 10,
					'tanggal' => now(),
					'saldo_awals_id' => 8,
					'crj_id' => null,
					'cpj_id' => null,
					'purchasejournal_id' => null,
					'salesjournal_id' => null,
					'retur_penjualan_id' => null,
					'retur_pembelian_id' => null,
					'cash_bank_ins_id' => null,
					'cash_bank_outs_id' => null,
					'jurnal_umums_id' => null,
					'pettycash_id' => null,
					'jurnalpenyesuaians_id' => null,
					'debet'      => 670000000,
					'kredit'     => 0,
					'created_at' => now(),
					'updated_at' => now(),
				],
				[
					'account_id' => 12,
					'tanggal' => now(),
					'saldo_awals_id' => 9,
					'crj_id' => null,
					'cpj_id' => null,
					'purchasejournal_id' => null,
					'salesjournal_id' => null,
					'retur_penjualan_id' => null,
					'retur_pembelian_id' => null,
					'cash_bank_ins_id' => null,
					'cash_bank_outs_id' => null,
					'jurnal_umums_id' => null,
					'pettycash_id' => null,
					'jurnalpenyesuaians_id' => null,
					'debet'      => 320000000,
					'kredit'     => 0,
					'created_at' => now(),
					'updated_at' => now(),
				],
				[
					'account_id' => 13,
					'tanggal' => now(),
					'saldo_awals_id' => 10,
					'crj_id' => null,
					'cpj_id' => null,
					'purchasejournal_id' => null,
					'salesjournal_id' => null,
					'retur_penjualan_id' => null,
					'retur_pembelian_id' => null,
					'cash_bank_ins_id' => null,
					'cash_bank_outs_id' => null,
					'jurnal_umums_id' => null,
					'pettycash_id' => null,
					'jurnalpenyesuaians_id' => null,
					'debet'      => 0,
						'kredit'     => 30000000,//30500000
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 14,
						'tanggal' => now(),
						'saldo_awals_id' => 11,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 160000000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 15,
						'tanggal' => now(),
						'saldo_awals_id' => 12,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 10000000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 16,
						'tanggal' => now(),
						'saldo_awals_id' => 13,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 130000000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 17,
						'tanggal' => now(),
						'saldo_awals_id' => 14,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 42000000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 18,
						'tanggal' => now(),
						'saldo_awals_id' => 15,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 154000000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 19,
						'tanggal' => now(),
						'saldo_awals_id' => 16,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 1875000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 22,
						'tanggal' => now(),
						'saldo_awals_id' => 17,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 133000000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 23,
						'tanggal' => now(),
						'saldo_awals_id' => 18,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 112200000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 24,
						'tanggal' => now(),
						'saldo_awals_id' => 19,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 200000000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 25,
						'tanggal' => now(),
						'saldo_awals_id' => 20,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 1030000000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 26,
						'tanggal' => now(),
						'saldo_awals_id' => 21,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 124200000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 27,
						'tanggal' => now(),
						'saldo_awals_id' => 22,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 22000000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 29,
						'tanggal' => now(),
						'saldo_awals_id' => 23,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 1093200000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 31,
						'tanggal' => now(),
						'saldo_awals_id' => 24,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 15000000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 33,
						'tanggal' => now(),
						'saldo_awals_id' => 25,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 17000000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 34,
						'tanggal' => now(),
						'saldo_awals_id' => 26,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 674880000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 36,
						'tanggal' => now(),
						'saldo_awals_id' => 27,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 2440000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 37,
						'tanggal' => now(),
						'saldo_awals_id' => 28,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 2180000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 38,
						'tanggal' => now(),
						'saldo_awals_id' => 29,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 44000000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 40,
						'tanggal' => now(),
						'saldo_awals_id' => 30,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 10800000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 43,
						'tanggal' => now(),
						'saldo_awals_id' => 31,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 15200000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 44,
						'tanggal' => now(),
						'saldo_awals_id' => 32,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 9750000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 46,
						'tanggal' => now(),
						'saldo_awals_id' => 33,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 40250000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 47,
						'tanggal' => now(),
						'saldo_awals_id' => 34,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 13000000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 49,
						'tanggal' => now(),
						'saldo_awals_id' => 35,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 53000000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 50,
						'tanggal' => now(),
						'saldo_awals_id' => 36,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 7000000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 51,
						'tanggal' => now(),
						'saldo_awals_id' => 37,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 0,
						'kredit'     => 17000000,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 52,
						'tanggal' => now(),
						'saldo_awals_id' => 38,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 8140000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 53,
						'tanggal' => now(),
						'saldo_awals_id' => 39,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 15000000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'account_id' => 54,
						'tanggal' => now(),
						'saldo_awals_id' => 40,
						'crj_id' => null,
						'cpj_id' => null,
						'purchasejournal_id' => null,
						'salesjournal_id' => null,
						'retur_penjualan_id' => null,
						'retur_pembelian_id' => null,
						'cash_bank_ins_id' => null,
						'cash_bank_outs_id' => null,
						'jurnal_umums_id' => null,
						'pettycash_id' => null,
						'jurnalpenyesuaians_id' => null,
						'debet'      => 10932000,
						'kredit'     => 0,
						'created_at' => now(),
						'updated_at' => now(),
					],
				];
				DB::table('laporan_buku_besar_penyesuaians')->truncate();
				DB::table('laporan_buku_besar_penyesuaians')->insert($data);
    }
}
