<?php

use Illuminate\Database\Seeder;

class SaldoAwalsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
          [
            'account_id' => 1,
            'tanggal' => now(),
            'debet'      => 264463000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 2,
            'tanggal' => now(),
            'debet'      => 6000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 4,
            'tanggal' => now(),
            'debet'      => 110000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 5,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 7200000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 6,
            'tanggal' => now(),
            'debet'      => 180000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 7,
            'tanggal' => now(),
            'debet'      => 13600000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 9,
            'tanggal' => now(),
            'debet'      => 8000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 10,
            'tanggal' => now(),
            'debet'      => 670000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 12,
            'tanggal' => now(),
            'debet'      => 320000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 13,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 30000000,//30500000
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 14,
            'tanggal' => now(),
            'debet'      => 160000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 15,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 10000000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 16,
            'tanggal' => now(),
            'debet'      => 130000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 17,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 42000000,//43000000
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 18,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 154000000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 19,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 1875000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 22,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 133000000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 23,
            'tanggal' => now(),
            'tanggal' => now(),
            'debet'      => 112200000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 24,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 200000000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 25,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 1030000000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 26,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 124200000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 27,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 22000000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 29,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 1093200000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 31,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 15000000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 33,
            'tanggal' => now(),
            'debet'      => 17000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 34,
            'tanggal' => now(),
            'debet'      => 674880000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 36,
            'tanggal' => now(),
            'debet'      => 2440000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 37,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 2180000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 38,
            'tanggal' => now(),
            'debet'      => 44000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 40,
            'tanggal' => now(),
            'debet'      => 10800000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 43,
            'tanggal' => now(),
            'debet'      => 15200000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 44,
            'tanggal' => now(),
            'debet'      => 9750000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 46,
            'tanggal' => now(),
            'debet'      => 40250000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 47,
            'tanggal' => now(),
            'debet'      => 13000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 49,
            'tanggal' => now(),
            'debet'      => 53000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 50,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 7000000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 51,
            'tanggal' => now(),
            'debet'      => 0,
            'kredit'     => 17000000,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 52,
            'tanggal' => now(),
            'debet'      => 8140000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 53,
            'tanggal' => now(),
            'debet'      => 15000000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
          [
            'account_id' => 54,
            'tanggal' => now(),
            'debet'      => 10932000,
            'kredit'     => 0,
            'created_at' => now(),
    				'updated_at' => now(),
          ],
        ];
        DB::table('saldo_awals')->truncate();
    	DB::table('saldo_awals')->insert($data);
    }
}
